name = "Patents"
uuid = "d01f8802-a735-4783-851a-d2cff8aa012a"
authors = ["Jakob Hoffmann"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
